[package]
name = "fuser-lab"
version = "0.1.0"
edition = "2021"

[dependencies]
fuser = "0.14"
clap = { version = "4.5", features = ["cargo", "derive"] }
libc = "0.2.155"
env_logger = "0.11.3"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
